### ISSUE TITLE
Edit User model

### ISSUE THREAD

**Issue by navase** [mikadamsterdam/Voyage#4]
- Add first_name, last_name, image, country, city, biography
- Look at User controller and views (from Devise), maybe change thinks

**Comment by mikadamsterdam** [comment]
http://stackoverflow.com/questions/10167679/best-way-to-add-attributes-to-user-model-in-ruby-on-rails
I did follow this explanation to add the other attributes to the profile already created with "devise"
I did not create a new controller for 20160216145255_add_details_to_user.rb as it is linked to devise and visible in schema. so, it should work.

regarding devise:
mikael@mikael-HP-Pavilion-15-Notebook-PC:~/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/devise-3.4.1/lib/devise/controllers$
check this link for more explanations:
https://github.com/plataformatec/devise/tree/master/lib/devise/controllers
